# Generated by Django 3.2.4 on 2021-07-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='EmployeePesonalDetail',
        ),
    ]
