# Generated by Django 3.2.4 on 2021-07-15 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapp', '0002_auto_20210715_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('CNIC', models.CharField(blank=True, max_length=13, unique=True)),
                ('FatherName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=8)),
                ('MaritalStatus', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryAddress', models.CharField(max_length=100)),
                ('ExpectedTime', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField(auto_now=True)),
                ('CustomerOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.employee')),
            ],
        ),
    ]
